# Generated by Django 2.2 on 2019-04-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('multiverse_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.IntegerField(choices=[(0, 'common'), (1, 'uncommon'), (2, 'rare'), (3, 'mythic')], default=0)),
                ('card_type', models.CharField(max_length=200)),
                ('toughness', models.CharField(max_length=200)),
                ('power', models.CharField(max_length=200)),
                ('cmc', models.BigIntegerField(default=0)),
                ('text_vector_1', models.FloatField(default=0.0)),
                ('text_vector_2', models.FloatField(default=0.0)),
                ('text_vector_3', models.FloatField(default=0.0)),
                ('color_identity', models.IntegerField(choices=[(0, 'C'), (1, 'R'), (2, 'U'), (3, 'G'), (4, 'B'), (5, 'W'), (6, 'RU'), (7, 'RG'), (8, 'RB'), (9, 'RW'), (10, 'UG'), (11, 'UB'), (12, 'UW'), (13, 'GB'), (14, 'GW'), (15, 'BW'), (16, 'RUG'), (17, 'RUB'), (18, 'RUW'), (19, 'RGB'), (20, 'RGW'), (21, 'RBW'), (22, 'UGB'), (23, 'UGW'), (24, 'UBW'), (25, 'GBW'), (26, 'RUGB'), (27, 'RUGW'), (28, 'RUBW'), (29, 'RGBW'), (30, 'UGBW'), (31, 'RUGBW')], default=0)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deck_size', models.BigIntegerField(default=0)),
                ('unique_count', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Deck_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
