# Generated by Django 2.2 on 2019-04-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cmc',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='multiverse_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='text_vector',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='toughness',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='unique_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
