# Generated by Django 2.2.1 on 2019-05-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_vector_point',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='deck_detail',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='deck_detail',
            old_name='deck_id',
            new_name='deck',
        ),
    ]
