# Generated by Django 2.2 on 2019-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_api', '0003_auto_20190414_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='text_vector',
            new_name='text_tsne_1',
        ),
        migrations.AddField(
            model_name='card',
            name='text_tsne_2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='text_tsne_3',
            field=models.BigIntegerField(default=0),
        ),
    ]
