# Generated by Django 2.2 on 2019-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_api', '0004_auto_20190414_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='card',
            name='color_identity',
            field=models.IntegerField(choices=[(0, 'C'), (1, 'R'), (2, 'U'), (3, 'G'), (4, 'B'), (5, 'W'), (6, 'RU'), (7, 'RG'), (8, 'RB'), (9, 'RW'), (10, 'UG'), (11, 'UB'), (12, 'UW'), (13, 'GB'), (14, 'GW'), (15, 'BW'), (16, 'RUG'), (17, 'RUB'), (18, 'RUW'), (19, 'RGB'), (20, 'RGW'), (21, 'RBW'), (22, 'UGB'), (23, 'UGW'), (24, 'UBW'), (25, 'GBW'), (26, 'RUGB'), (27, 'RUGW'), (28, 'RUBW'), (29, 'RGBW'), (30, 'UGBW'), (31, 'RUGBW')], default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.CharField(max_length=200),
        ),
    ]
