# Generated by Django 2.2 on 2019-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_api', '0005_auto_20190415_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
