# Generated by Django 2.2 on 2019-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_api', '0006_auto_20190415_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='text_tsne_1',
        ),
        migrations.RemoveField(
            model_name='card',
            name='text_tsne_2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='text_tsne_3',
        ),
        migrations.AddField(
            model_name='card',
            name='text_vector_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='text_vector_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='text_vector_3',
            field=models.FloatField(default=0.0),
        ),
    ]
