# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  postgresql:
    image: postgres:14.5
    volumes:
     - data:/var/lib/postgresql/data/
     - ./postgres/migrations/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=magic
      - POSTGRES_PASSWORD=magic
      - POSTGRES_DB=magic
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
volumes:
  data: {}
