# Generated by Django 3.0.3 on 2020-03-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic_api', '0004_auto_20190519_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck_detail',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_api.Card', to_field='name'),
        ),
    ]
