# Generated by Django 3.0.3 on 2020-06-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_api', '0005_auto_20200302_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_vector_point',
            name='card',
            field=models.CharField(max_length=200),
        ),
    ]
